# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CreditCardList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Kingfisher', '~> 7.8'
	pod 'lottie-ios', '~> 4.2'
	pod 'FirebaseDatabase', '~> 10.11'
	
  # Pods for CreditCardList

end
