# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteNotification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'FirebaseAnalytics', '~> 10.11'
	pod 'FirebaseMessaging', '~> 10.11'
  # Pods for RemoteNotification

end
