# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'FirebaseRemoteConfig', '~> 10.11'
	pod 'FirebaseAnalytics', '~> 10.11'

  # Pods for Notice

end
